#!/usr/bin/python

import os
from subprocess import call

for i in range(0,101,5):
  for j in range(1,21):
    text = './trading.strat.py -a %s -m %s -b 1' %(float(i)/100, float(j)/100)
    print text
    os.system(text)
